language: cpp
compiler: gcc

before_install:
  # install doxygen 1.8.11 from binary, because older versions throw errors on markdown code with images inside links
  # (like the build status in the readme) and it's the only way to get a newer doxygen in Ubuntu 14.04
  # doxygen binary installation based on https://github.com/gadomski/fgt/blob/master/scripts/gh-pages.sh
  - export DOXYGEN_VER=doxygen-1.8.11
  - export DOXYGEN_TAR=${DOXYGEN_VER}.linux.bin.tar.gz
  - export DOXYGEN_URL="http://ftp.stack.nl/pub/users/dimitri/${DOXYGEN_TAR}"
  # for new boost (1.55)
  - sudo add-apt-repository --yes ppa:boost-latest/ppa
  # for new gcc (4.8)
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  # for new cairo
  - sudo add-apt-repository --yes ppa:ricotz/testing
  # for new cmake
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  # for doxygen (1.8.8) (still too old)
  # - sudo add-apt-repository --yes ppa:kedazo/doxygen-updates-precise

  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake g++-4.8 libboost1.55-all-dev libboost-log1.55-dev libcairo2-dev libpng12-dev asciidoc
  # - sudo apt-get install -qq doxygen

  #if GCC
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - sudo pip install ghp-import
  - wget -O - "${DOXYGEN_URL}" | tar xz -C ${TMPDIR-/tmp} ${DOXYGEN_VER}/bin/doxygen
  - export PATH="${TMPDIR-/tmp}/${DOXYGEN_VER}/bin:$PATH"
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTING=ON

script:
  - make
  - ctest -VV -E unitTests_renderer
  - make doc

after_success:
  - cd ..
  - ./.travis-publish-docs.sh

notifications:
  email:
    recipients:
      - alacarte-fail@mixaill.tk
    on_success: change
    on_failure: always
