language: cpp
os:
  -linux

dist: trusty
sudo: required

before_install:
  # install doxygen 1.8.11 from binary, because older versions throw errors on markdown code with images inside links
  # (like the build status in the readme) and it's the only way to get a newer doxygen in Ubuntu 14.04
  # doxygen binary installation based on https://github.com/gadomski/fgt/blob/master/scripts/gh-pages.sh
  - export DOXYGEN_VER=doxygen-1.8.11
  - export DOXYGEN_TAR=${DOXYGEN_VER}.linux.bin.tar.gz
  - export DOXYGEN_URL="http://ftp.stack.nl/pub/users/dimitri/${DOXYGEN_TAR}"

  # for new gcc (4.8, 4.9, 5.4, 6.2)
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test

  # for new clang
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" | sudo tee -a /etc/apt/sources.list

  # for new cairo (1.14.2)
  - sudo add-apt-repository --yes ppa:ricotz/testing
  
  # for new cmake (3.2)
  - sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x

  - sudo apt-get update -qq

  - sudo apt-get install -qq $SUPPORT $PACKAGE
  - sudo apt-get install -qq cmake libboost1.55-all-dev libboost-log1.55-dev libcairo2-dev libpng12-dev asciidoc

  - export CC=${REAL_CC} CXX=${REAL_CXX}

before_script:
  - sudo pip install ghp-import
  - wget -O - "${DOXYGEN_URL}" | tar xz -C ${TMPDIR-/tmp} ${DOXYGEN_VER}/bin/doxygen
  - export PATH="${TMPDIR-/tmp}/${DOXYGEN_VER}/bin:$PATH"

  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTING=ON

script:
  - make -j2
  - ctest -VV -E unitTests_renderer
  - make doc

env:
  matrix:
    - ignore=this

matrix:
  exclude:
    - env: ignore=this

  include:
    - os: linux
      compiler: clang
      env: PLATFORM='linux' REAL_CC=clang-3.9 REAL_CXX=clang++-3.9 PACKAGE=clang-3.9 SUPPORT=libstdc++-5-dev

    - os: linux
      compiler: gcc
      env: PLATFORM='linux' REAL_CC=gcc-5     REAL_CXX=g++-5       PACKAGE=g++-5     SUPPORT=

    - os: linux
      compiler: gcc
      env: PLATFORM='linux' REAL_CC=gcc-4.9   REAL_CXX=g++-4.9     PACKAGE=g++-4.9   SUPPORT=


after_success:
  - cd ..
  - ./.travis-publish-docs.sh

notifications:
  email:
    recipients:
      - alacarte-fail@mixaill.tk
    on_success: change
    on_failure: always
